# Generated by Django 3.2.8 on 2021-11-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeer', '0002_auto_20211113_1514'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Employer',
        ),
    ]
