# Generated by Django 3.2.8 on 2021-11-13 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeer', '0003_rename_employee_employer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
