# Generated by Django 3.2.8 on 2021-11-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(error_messages={'unique': 'user already exist'}, max_length=254, unique=True)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('role', models.CharField(default='Employer', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='employer',
            name='role',
            field=models.CharField(default='Employer', max_length=10),
        ),
    ]
